version: '3.9'

services:
  fcm-backend:
    image: fcm-backend:latest
    build:
      target: runner
    ports:
      - '3002:3000'
    env_file:
      - .env
    restart: always
networks:
  intranet:
