version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-be
    restart: always
    environment:
      PORT: 3002
    ports:
      - '3002:3002'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - default_network

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: fmcuser
      POSTGRES_PASSWORD: fcmpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default_network

volumes:
  postgres_data:

networks:
  default_network:
    driver: bridge