version: '3.3'

services:
  fcm-backend:
    image: fcm-backend:latest
    build:
      context: .
      #target: runner
    ports:
      - '3002:3000'
    # env_file:
    #  - .env
    restart: always
networks:
  intranet:
